"""Memória de aprendizado do PySusNoCode.

Cada vez que o aplicativo encontra um erro ao executar uma célula e consegue
corrigi-lo, extrai uma "lição" (uma linha) e guarda aqui. As lições são
injetadas no prompt de sistema das próximas conversas, de modo que o app
aprende com os próprios erros entre sessões.
"""

from __future__ import annotations

import json
import unicodedata
from datetime import date

from .config import APP_DIR, LESSONS_FILE

# Teto de lições que vão para o prompt. Precisa folgar sobre a quantidade de
# lições pré-carregadas, porque essas nunca são cortadas — a folga é o espaço
# das lições que o aplicativo aprendeu sozinho.
MAX_LESSONS_IN_PROMPT = 100
MAX_LESSONS_STORED = 250

# Lições pré-carregadas com armadilhas conhecidas do PySUS em notebooks.
SEED_LESSONS = [
    "As funcoes do pysus chamam asyncio.run() por dentro e falham em qualquer notebook ('asyncio.run() cannot be called from a running event loop'). Antes de usar a biblioteca rode: import nest_asyncio; nest_asyncio.apply().",
    "A primeira celula de codigo deve ser '%pip install pysus==2.10.6 nest_asyncio -q' e a segunda 'import nest_asyncio; nest_asyncio.apply()' — funciona neste aplicativo e no Google Colab. FIXE a versao: sem o numero, o notebook instala a mais recente e roda contra uma biblioteca diferente da que foi validada. A PySUS publicou seis versoes em cinco dias, e uma delas mudou o catalogo a ponto de tres exemplos passarem a devolver o Brasil inteiro rotulado como Parana.",
    "O parametro group so funciona no CNES. Em SIH, SIM, SINASC e SIA, passar group faz a funcao devolver ZERO linhas: nessas bases nao passe group.",
    "No CNES o group e essencial: sem ele o download traz 33 mil linhas e 362 colunas (mais de 300 MB) com todos os grupos misturados. Use group='LT' para leitos, 'ST' para estabelecimentos, 'PF' para profissionais.",
    "Pedir um periodo inexistente no catalogo devolve tabela VAZIA, sem erro. Consulte antes com list_files(dataset=..., state=..., year=...) e verifique len(df) depois de baixar.",
    "SINAN e nacional (nao aceita state) e gigantesco: dengue de 2024 tem 6,5 milhoes de linhas e ~29 GB em memoria se carregada inteira. Use as_dataframe=False e leia so as colunas necessarias com pd.read_parquet(caminho, columns=[...]).",
    "SG_UF_NOT do SINAN vem como codigo IBGE em texto ('35'=SP, '31'=MG, '41'=PR), nao como sigla.",
    "Na base CIHA o parametro group tem 'CIHA' como valor padrao, e esse valor faz a consulta devolver ZERO linhas: e preciso passar group=None explicitamente.",
    "SIA e enorme: um unico mes de um estado grande passa de 3 milhoes de linhas e 253 colunas. Use as_dataframe=False e leia so as colunas necessarias (PA_PROC_ID, PA_QTDAPR, PA_VALAPR, PA_MUNPCN).",
    "O grupo PA (producao ambulatorial) do SIA nao existe em todos os estados e meses; confira antes no catalogo com list_files(dataset='sia', state=..., year=...).",
    "Para resumos de bases grandes, duckdb consulta o parquet sem carregar nada na memoria: duckdb.sql(\"SELECT col, COUNT(*) FROM read_parquet('caminho') GROUP BY col\"). No GROUP BY use o nome original da coluna, nao o apelido do SELECT.",
    "A populacao para calcular taxas por 100 mil habitantes vem de ibge(year=...), com colunas UFCOD, IDADE, SEXO e POPULACAO.",
    "Se o Python for encerrado durante uma celula, quase sempre foi falta de memoria por carregar uma base inteira: refaca com recorte menor ou lendo apenas as colunas necessarias.",
    "sinan(disease=...) so aceita a SIGLA DE QUATRO LETRAS. Passar o nome do agravo devolve ZERO arquivo, sem erro nenhum — e o nome que falha e exatamente o que a propria biblioteca usa no dicionario dela ('MENI': 'Meningite'). Medido na 2.10.6 em tres agravos: disease='DENG' devolve DENGBR24 e disease='Dengue' devolve lista vazia; o mesmo com MENI/Meningite e LEPT/Leptospirose, embora list_files(dataset='sinan', group='MENI', year=2024) ache o arquivo. Quem escrever o nome por extenso conclui que nao ha dado para aquele agravo. Use SEMPRE a sigla.",
    "Prefira as funcoes de alto nivel do pysus 2.x com as_dataframe=True para receber um pandas.DataFrame pronto (ex.: sinan(disease='DENG', year=2024, as_dataframe=True)).",
    "Downloads do DATASUS podem demorar varios minutos; em testes iniciais baixe apenas 1 ano e, quando o dataset for estadual, apenas 1 UF.",
    "Codigo encontrado na internet com 'from pysus.online_data import ...' ou 'from pysus.ftp.databases ...' e da versao 1.x (antiga). Na 2.x use 'from pysus import sinan, sim, ...' ou o orquestrador pysus.api.client.PySUS.",
    "Colunas de DataFrames do DATASUS geralmente vem como texto (dtype object). Converta com pd.to_numeric(..., errors='coerce') ou pd.to_datetime(..., errors='coerce') antes de agregar ou plotar.",
    "Datas do SINAN como DT_NOTIFIC podem vir no formato YYYYMMDD; use pd.to_datetime(df['DT_NOTIFIC'], format='%Y%m%d', errors='coerce').",
    "O pysus devolve o caminho de um ARQUIVO .parquet, nao de uma pasta. No duckdb use read_parquet('caminho.parquet'); acrescentar '/**/*.parquet' da erro 'No files found that match the pattern'.",
    "A populacao municipal do IBGE (POPTBR) de 2022 e de 2023 esta TRUNCADA na origem: 2022 so tem o Parana (399 municipios) e 2023 so o Rio Grande do Norte (167). Antes de calcular taxa municipal, confira que o arquivo tem 5570 municipios e 27 UFs; se nao tiver, use outro ano ou trabalhe por UF com as projecoes (PROJUF), que estao completas.",
    "A idade no SIM e um codigo de 3 digitos, nao um numero de anos: o primeiro digito e a unidade (0-3 = minutos, horas, dias e meses, ou seja, menos de 1 ano; 4 = anos; 5 = anos acima de 100). Tratar IDADE como inteiro produz idades de 400 anos. Decodifique antes de usar.",
    "Ao comparar taxas entre estados, municipios ou anos, ofereca padronizacao por idade: a taxa bruta compara estruturas etarias, nao risco. Exemplo real: RS tem mortalidade bruta de 833 por 100 mil contra 491 do AP, mas depois de padronizar o AP fica pior (630 contra 546).",
    "No SIA, os procedimentos de atencao basica aparecem com valor aprovado ZERO (PA_VALAPR): eles sao pagos por bloco de financiamento, nao por procedimento. Somar valor do SIA e concluir que a atencao primaria e barata e erro de leitura — avise o usuario disso ao mostrar gasto por nivel de complexidade (campo PA_NIVCPL: 1 basica, 2 media, 3 alta).",
    "O codigo de procedimento do SIGTAP (PA_PROC_ID no SIA, PROC_REA no SIH e no CIHA) e estruturado: os 2 primeiros digitos sao o grupo (01 promocao, 02 diagnostico, 03 clinico, 04 cirurgico, 05 transplantes, 06 medicamentos, 07 orteses e proteses, 08 acoes complementares) e os 4 primeiros o subgrupo (0301 consultas, 0304 oncologia, 0305 nefrologia/dialise, 0202 laboratorio, 0206 tomografia, 0207 ressonancia). Da para classificar milhoes de linhas com substr(), sem tabela auxiliar.",
    "A pysus 2.10 tem pysus.info() e pysus.info_table(), que listam 34 conjuntos de dados de tres origens. So as 9 bases de origem FTP (SINAN, SIM, SINASC, SIH, SIA, CNES, PNI, CIHA, IBGE) tem ARQUIVOS para baixar; as 6 de origem 'DadosGov' exigem autenticacao. As 19 de origem 'Saude' devolvem zero arquivos porque NAO SAO ARQUIVOS: elas vem do portal dadosabertos.saude.gov.br e da API REST apidadosabertos.saude.gov.br. Os dados existem e estao atualizados — 'zero arquivos' nunca significa 'sem dados', significa que a fonte e servida por outro caminho.",
    "As funcoes da origem 'Saude' da pysus devolvem lista vazia (reconferido na 2.10.6 em 29/08/2026: 9 de 11 vazias — atencao_primaria, bnafar, vacinacao, assistencia_saude, prevencao_promocao, ouvidoria, saude_indigena e covid19). Sao DUAS causas, e nenhuma e 'erro de chave': (1) o download so aceita URL terminada em '.csv' e o portal publica em .zip — no grupo atencao-primaria ha ZERO recursos .csv entre os 95; (2) o mapa de grupos CKAN erra alvos: atencao_primaria aponta para um grupo que nao contem SISAB nenhum, e sisvan aponta para 'saude-indigena', devolvendo dado do grupo errado com cara de certo. vigilancia_meio_ambiente ainda existe como funcao mas a base foi removida na 2.10.5: devolve zero. Para atencao primaria use SaudeClient (list_datasets/fetch_dataset) ou o Relatorio de Validacao do SISAB.",
    "pysus.quality_score() melhorou entre a 2.10.3 e a 2.10.6, mas ainda engana na parte que importa: a COMPLETUDE continua dando 100% para uma tabela cheia de campos em branco, porque o DATASUS grava vazio como STRING VAZIA e nao como nulo. O que mudou e que agora existe uma dimensao 'validity' que pega isso (0,33 e 0,67 no meu teste) e derruba o overall para 80. Entao: nao cite completeness como prova de qualidade; olhe validity, e conte as strings vazias voce mesmo com (df[col].astype(str).str.strip() == ''). O mesmo cuidado vale para missing_values().",
    "Nao confie em pysus.validate_data() para idade: a regra embutida testa se o valor esta entre 0 e 120 e aprova a coluna IDADE do SIH, que sozinha nao quer dizer nada (precisa de COD_IDADE para saber se sao dias, meses ou anos). Ela valida a forma, nao o significado.",
    "Evite pysus.to_english(): ele traduz apenas parte dos nomes das colunas e devolve uma tabela com metade em portugues e metade em ingles (IDADE vira 'age' mas COD_IDADE fica como esta, o que e justamente a armadilha). Pior que qualquer um dos dois idiomas sozinho.",
    "pysus.load_column_metadata(base) so serve para SINAN, SIM, SINASC, SIH e arboviroses. Reconferido na 2.10.6: pedir 'SIA' devolve 24 colunas que sao do SIH (N_AIH, UF_ZI, ANO_CMPT) e NENHUMA PA_*; pedir 'CNES' devolve zero. Ou seja, para as duas bases mais usadas em analise ambulatorial e de estabelecimento a funcao entrega o schema errado ou nada — e sem avisar. Mesmo onde funciona ela NAO devolve as tabelas de codigo, mas elas EXISTEM: o pacote embarca 35 esquemas YAML com 1.963 colunas, das quais 1.105 trazem as categorias em portugues. A funcao simplesmente nao as expoe — e pior, ignora o segundo argumento: load_column_metadata('sinan','Dengue'), ('sinan','Tuberculose') e ate um agravo inexistente devolvem as MESMAS 1.238 chaves, nenhuma com categories. Para usar as categorias, leia o YAML direto de pysus/api/metadata/schemas/<base>/<arquivo>.yaml (caminho interno, pode mudar de versao — confira que existe antes de depender dele).",
    "pysus.disable_progress_bars() existe desde a 2.10 e promete desligar as barras de download, mas NAO TEM EFEITO — testado na 2.10.3, as barras continuam saindo em stderr. Nao ofereca essa funcao ao usuario como solucao para a saida poluida.",
    "nest_asyncio.apply() so faz sentido DENTRO de um notebook (Jupyter/Colab/este aplicativo), onde ja existe um laco de eventos rodando. Num script .py comum ele e desnecessario — a pysus funciona sem ele — e tem um efeito colateral ruim: o laco remendado nunca fecha e o Python NAO ENCERRA sozinho depois da ultima linha; o processo fica parado consumindo memoria ate ser morto a forca. Se o usuario pedir para transformar a analise num script para rodar sozinho (agendado, por linha de comando), retire o nest_asyncio.",
    "Bases diferentes fecham em anos diferentes: no Parana o SIM ja tem 2024 e o SINASC para em 2022. Ao cruzar duas bases (mortalidade infantil, por exemplo), use a INTERSECAO dos anos disponiveis, nunca o ano mais recente de uma delas — senao o numerador e de um ano e o denominador de outro.",
    "Nao use pd.set_option('display.float_format', ...) global: ele arredonda todos os numeros mostrados e esconde valores pequenos (0,0886 vira 0,09). Formate coluna a coluna com .round() quando precisar.",
    "Para separar milhar no padrao brasileiro NAO use f\"{n:,}\".replace(',', '.') dentro de uma frase: o replace troca tambem as virgulas do texto ('doencas, entre' vira 'doencas. entre'). Defina def mil(n): return f'{n:,.0f}'.replace(',', '.') e chame mil(n) dentro do f-string.",
    "Nunca adivinhe o significado dos codigos do DATASUS (ESC2010, RACACOR, GESTACAO, CONSULTAS, LOCOCOR...). Um rotulo deslocado produz uma tabela inteiramente errada sem nenhum erro de execucao. Mostre a distribuicao real (value_counts) e confira se ela faz sentido antes de rotular.",
    "sih(uf, ano, mes) devolve uma LISTA de arquivos e o primeiro costuma ser o SP (servicos profissionais, um registro por ato medico), nao o RD (uma linha por internacao, com DIAG_PRINC, DIAS_PERM, VAL_TOT e MORTE). Escolha pelo nome do arquivo: [c for c in caminhos if os.path.basename(c).upper().startswith('RD')].",
    "A cobertura do grupo RD do SIH no espelho do PySUS e esburacada: em alguns estados ha so 1 ou 2 meses por ano recente, enquanto o SP tem os 12. Consulte list_files(dataset='sih', state=UF, year=ANO) e conte os arquivos que comecam com RD antes de prometer uma analise anual.",
    "O PNI no PySUS termina em 2019 (arquivos CPNI e DPNI). Pedir 2020 ou depois devolve lista vazia sem erro.",
    "Os arquivos do SINAN nao tem as mesmas colunas entre agravos: a dengue de 2024 tem 121 colunas e o zika 38; HOSPITALIZ existe na dengue e na chikungunya, nao no zika. Consulte DESCRIBE antes de montar a consulta em vez de supor.",
    "As datas do SINAN (DT_NOTIFIC, DT_SIN_PRI) vem como TEXTO no parquet: strftime e date_diff falham com 'No function matches'. Converta com TRY_CAST(DT_SIN_PRI AS DATE). Campos numericos como NU_IDADE_N tem strings vazias: use TRY_CAST, nao CAST, senao a consulta inteira quebra.",
    "No SINAN, 'caso provavel' (o numero dos boletins do Ministerio da Saude) e notificacoes menos descartados pelo campo CLASSI_FIN — mas o CODIGO DO DESCARTE MUDA POR AGRAVO: 8 na dengue, 5 na chikungunya, 2 no zika. Usar um codigo so nas tres infla a chikungunya em mais de 60%. Para descobrir o codigo sem a tabela oficial, agrupe por CLASSI_FIN e veja onde estao os obitos: o descarte e o codigo em que praticamente ninguem morre.",
    "A idade no SINAN e NU_IDADE_N, com 4 digitos: o primeiro e a unidade (1 hora, 2 dia, 3 mes, 4 ano) e os tres seguintes o valor. 24 anos vem como '4024'.",
    "A idade no SIH vem em DOIS campos: IDADE (o numero) e COD_IDADE (a unidade: 2 dias, 3 meses, 4 anos, 5 anos acima de cem). Um recem-nascido de 3 dias aparece como idade 3. Combine os dois antes de calcular media ou faixa etaria.",
    "O grupo PF do CNES tem uma linha por VINCULO de trabalho, nao por pessoa: no PR sao 351 mil vinculos para 226 mil profissionais. Calcular 'medicos por mil habitantes' contando linhas infla o resultado em 3,6 vezes. Use count(DISTINCT CPF_PROF). Medicos sao os CBO que comecam com 225; enfermeiros, 2235.",
    "O campo REGSAUDE do CNES vem escrito de formas diferentes para a mesma regiao ('2a', '02', '002'). Normalize extraindo os digitos antes de agrupar, senao 22 regioes de saude viram 40.",
    "No CNES, TP_LEITO=3 e 'leito complementar', que inclui UTI E unidades intermediarias — nao chame de UTI. Para isolar a UTI e preciso o campo CODLEITO.",
    "Ao estratificar por escolaridade em bases de mortalidade, fixe a faixa etaria antes de comparar: a escolaridade carrega a geracao junto, e quem morreu com 80 anos ou mais quase nunca estudou. Sem esse cuidado o resultado sai invertido ('quem nao estudou vive mais'). Sem populacao por escolaridade nao ha taxa: compare composicao de causas (mortalidade proporcional) e diga isso ao usuario.",
    # --- a regressao do state= (agosto de 2026) -------------------------
    "sih(UF, ano, mes) devolve QUATRO arquivos e ler os quatro juntos infla a contagem em 14 vezes. Medido no PR, jan/2024: SP (servicos profissionais) tem 1.094.419 linhas, RD (AIH reduzida, que E a internacao) tem 81.125, ER 2.514 e RJ 2.131. Um notebook nosso concatenava tudo e publicava 1.170.669 'internacoes' quando sao 80.026 — e a letalidade hospitalar saia 0,3% quando o correto e 3,82%. Um numero desses num relatorio de gestao faz um hospital parecer dez vezes mais seguro do que e. SEMPRE filtre pelo prefixo RD (ou peca group='RD') antes de contar internacao. Vale a mesma disciplina do SIA: no SIH a familia do arquivo muda o que a linha significa.",
    "Para SIM e SINASC, NAO use sim(UF, ano)[0] nem sinasc(UF, ano)[0]: o primeiro da lista costuma ser o arquivo NACIONAL. Conferido no catalogo de 2026: de 1996 a 2021 vem o nacional (Mortalidade_Geral_AAAA) mais o estadual (DOPRAAAA); de 2022 a 2024 vem DO22OPEN (nacional) mais DOPR2022; e para 2025 e 2026 vem SO o nacional — nao existe arquivo estadual. Entao, em qualquer ano recente, [0] entrega o Brasil inteiro rotulado como estado. Escolha pelo NOME: o arquivo do estado comeca com DO+UF (SIM) ou DN+UF (SINASC). E prefira o ano mais recente que TENHA arquivo estadual — que e tambem um ano fechado, porque 2025 e 2026 ainda estao em andamento e subestimam qualquer contagem.",
    "O parametro state= diz onde PROCURAR, mas NAO FILTRA o resultado. Desde 2026 o catalogo publica um arquivo NACIONAL ao lado do arquivo de cada estado, e a pysus devolve os dois: sinasc(state='PR', year=2022) traz SINASC_2022.parquet junto com DNPR2022.parquet, o que da 2,7 milhoes de linhas do Brasil inteiro em vez das 140.637 do Parana — e ainda conta o PR duas vezes. Vale para sinasc e sim. SEMPRE confira de que UF sao as linhas depois de baixar.",
    "Para ficar so com o estado pedido use o CATALOGO, nao o nome do arquivo: em list_files(dataset=..., state=UF, year=ANO) o arquivo nacional vem com a coluna state VAZIA e o do estado vem com a sigla. Procurar a sigla dentro do nome do arquivo e armadilha — 'DO23OPEN' (o arquivo nacional do SIM) contem 'PE'.",
    "drop_duplicates() NAO conserta a mistura do arquivo nacional com o estadual: as linhas dos dois arquivos nao sao byte a byte identicas, e as duplicatas continuam la. O jeito e escolher o arquivo certo antes de ler.",
    "Nem todo ano tem arquivo por estado: o SINASC de 2023 so tem o arquivo nacional. Quando so houver o nacional, filtre as linhas pelo codigo do IBGE do estado (os 2 primeiros digitos de CODMUNRES) e AVISE o usuario que filtrou.",
    # --- funcoes novas da 2.10 que enganam ------------------------------
    "pysus.aggregate_by_age_group(df, coluna, valor) aceita QUALQUER coluna numerica como se fosse idade e nao confere nada: passando o codigo da UF ela devolve alegremente faixas '0-5', '5-15', '15-30'. Nao use sem ter certeza de que a coluna e idade em anos.",
    "CRITERIO GERAL para saber se conta ou soma: procure a coluna de QUANTIDADE. Se a base tem uma (PA_QTDPRO e PA_QTDAPR no SIA, por exemplo), cada linha representa VARIAS ocorrencias e contar linhas subestima — some a quantidade. Se nao tem, a linha E o evento e contar esta certo: no SIH/RD uma linha e uma internacao (AIH), no SIM uma linha e um obito, no SINASC um nascimento. Ha um terceiro caso, o mais traicoeiro: a linha nao e o evento nem tem quantidade, e sim um VINCULO ou um REGISTRO REPETIDO da mesma entidade — o grupo PF do CNES tem uma linha por vinculo de trabalho e nao por pessoa, e o PA do SIA tem varias linhas pelo mesmo paciente. Nesses use count(DISTINCT identificador). Antes de contar qualquer coisa, responda em voz alta: uma linha desta tabela e o que, exatamente?",
    "As tres funcoes aggregate_* da pysus CONTAM LINHAS em vez de somar o value_col, e isso e o padrao. Medido na 2.10.6: aggregate_by_state(df, value_col='N') com valores 10 e 5 no PR devolve 2, nao 15 — so com agg_func='sum' devolve 15. Pior: aggregate_by_age_group e aggregate_by_period NAO TEM o parametro agg_func, entao pedem um value_col cujos valores sao incapazes de somar. Quem chamar aggregate_by_age_group(df, 'IDADE', 'OBITOS') recebe contagem de linhas com nome de obitos. E a mesma armadilha do SIA (nao conte linhas, some quantidades), agora embutida numa funcao cujo nome sugere o contrario: prefira df.groupby(...)[coluna].sum().",
    "pysus.detect_units() classifica TODAS as colunas numericas como 'kg' com confianca 0,5, inclusive codigo de UF e contagem de equipes. Nao serve para nada em dados do DATASUS.",
    "pysus.aggregate_by_period(df, coluna_data, valor) devolve ZERO LINHAS sem erro quando a coluna de data e texto — e no DATASUS ela quase sempre e. Converta com pd.to_datetime(..., errors='coerce') antes.",
    "pysus.to_geojson() num DataFrame sem as colunas de coordenada grava um FeatureCollection VAZIO e devolve sucesso. Confira sempre len(mapa['features']) depois de exportar.",
    "pysus.to_sql(df, nome_tabela) NAO grava banco nenhum: devolve o TEXTO de um CREATE TABLE. Para gravar de verdade use duckdb ou sqlite direto.",
    "Quando o esquema da pysus discorda do dado, NAO diga que a pysus errou — o mais provavel e que ela tenha copiado fielmente uma inconsistencia do proprio Ministerio. Caso conferido nos documentos oficiais: no SINAN meningite, o campo ANT_TRAUMA (traumatismo previo) aparece no esquema como '1. Sim 3. Nao 9.Ignorado', enquanto os cinco campos vizinhos do mesmo bloco (ANT_IMUNO, ANT_IRA, ANT_TUBE, ANT_INF_HO, ANT_OUTRO) usam 2 para Nao. O arquivo MENIBR24 traz 21.308 linhas com codigo 2 e NENHUMA com 3. Fomos as fontes: a FICHA DE INVESTIGACAO oficial (SVS, 15/10/2007), campo 34, traz uma legenda unica para o bloco inteiro — '1 - Sim 2 - Nao 9 - Ignorado', incluindo Traumatismo; ja o DICIONARIO DE DADOS SINAN NET v5 (revisado em julho/2010), pagina 4, e que traz '3. Nao' so nesse campo. O cabecalho do YAML da pysus diz '# Source: MENI.csv from SINAN metadata tarball': ela reproduziu o dicionario. Entao o diagnostico certo e CONFLITO ENTRE FONTES OFICIAIS, e a triangulacao (ficha + dado observado contra dicionario) justifica ler 2 como Nao — desde que a divergencia seja registrada no metodo. Regra geral: a deteccao automatica (maioria da coluna sem rotulo) serve para PARAR e ir aos documentos, nao para concluir quem errou.",
    "Os esquemas YAML embarcados na pysus so tem tabela de codigo para o SINAN. Inventario da 2.10.6: 35 esquemas, 1.963 colunas, 1.105 com categorias — e TODAS as 1.105 estao nos 28 agravos do SINAN (dengue 65 de 86 colunas, chikungunya 65, meningite 60, tuberculose 25 de 56). Os esquemas de SIA, SIH, SIM e SINASC existem mas tem ZERO categorias, e sao justamente as bases mais usadas. Conferido contra arquivo real (DENGBR24, 121 colunas): 78 das 86 do esquema casam (91%), e as categorias batem com os dados — FEBRE '1-Sim 2-Nao' e exatamente o que aparece. MAS o esquema e INCOMPLETO: CLASSI_FIN lista 5, 10, 11, 12, 13 e nao lista o codigo 8, que e o SEGUNDO valor mais frequente (542.641 registros, 7,6%); CS_SEXO nem esta no esquema. Use o esquema para rotular, mas confira sempre com value_counts o que sobrou sem rotulo, e mostre isso ao usuario.",
    "pysus.optimize_memory() NAO serve para dado do DATASUS. Ela so faz downcast de colunas que ja sao int ou float, e o parquet do DATASUS vem com tudo em texto. Medido no SIA/PA do AC (154.136 linhas, 60 colunas, todas object): 466 MB antes, 466 MB depois — ganho de 0,0%. O que funciona e converter as colunas de texto repetitivo para o tipo 'category': as mesmas 60 colunas caem de 466 MB para 12 MB, 97,4% de reducao. Faca df[col] = df[col].astype('category') nas colunas com poucos valores distintos, e nao perca tempo com optimize_memory.",
    "pysus.link_datasets(df1, df2, on=, how=) NAO faz record linkage: e literalmente pd.merge com sufixos _1 e _2 nas colunas repetidas (conferido no codigo-fonte da 2.10.6). Nao ha pareamento probabilistico, nem normalizacao de chave, nem tolerancia de data — nada do que 'linkage' significa em saude. Nao a use nem a cite: o nome promete o que ela nao faz, e renomear coluna em silencio ainda quebra o codigo seguinte. Ensine pd.merge, que o usuario entende e consegue conferir com len() depois.",
    "pysus.to_excel(df, caminho, metadata={...}) e util de verdade para o nosso publico: grava a planilha com uma aba 'Data' e outra 'Metadata' com os pares chave/valor que voce passar (fonte, UF, competencia, data da extracao). Conferido na 2.10.6. Profissional de saude vive no Excel, e mandar a planilha com a procedencia registrada dentro dela evita a pergunta 'de onde saiu esse numero?' tres meses depois. Existe tambem to_csv(df, caminho, metadata=...), que grava o metadado num arquivo ao lado.",
    "As funcoes de metadado da pysus prometem mais do que entregam (reconferido na 2.10.6): search_columns(dataset=..., query=...) so tem conteudo para 'sinan' — 120 resultados para 'idade', e ZERO para sih, sim, sinasc e sia; get_aliases() devolve lista vazia ate para SIH/IDADE; get_linking_keys() devolve lista vazia para todos os pares testados (SIH x SIM, SINASC x SIM, SIA x CNES, SIH x CNES); e available_databases() ainda lista 'vigilanciameioambiente', base REMOVIDA na 2.10.5. Nao apresente nenhuma delas como dicionario ou mapa de ligacao entre as bases.",
    "O que vale a pena da pysus 2.10, medido no arquivo real do SIA do PR (3,76 milhoes de linhas): query_parquet(caminho, sql) + to_df()/to_arrow() agregam via duckdb SEM carregar — 0,03 s e 140 bytes de resultado, contra 4,4 s e 11,11 GB para ler o arquivo inteiro com pd.read_parquet; stream_parquet(caminho, chunk_size, columns) le em pedacos com pico de 20 MB (1,4 s para percorrer tudo), mask_data()/unmask_data() criptografam e revertem colunas sensiveis com uma chave (util para compartilhar dado), column_stats() e profile_report() dao um retrato rapido de cada coluna.",
    # --- atencao primaria: onde os dados realmente estao ----------------
    "Os indicadores do Previne Brasil / SISAB estao na API REST apidadosabertos.saude.gov.br, no endpoint /atencao-primaria/indicador-desempenho-programa-previne-brasil, com filtros de uf, competencia, quadrimestre e codigo_municipio. O helper pysus.api.saude.rest.iter_rows pagina para voce.",
    "A paginacao por offset da API do Ministerio da Saude e INSTAVEL: ela desloca linhas sobre um resultado sem ordenacao garantida. Tres coletas seguidas do mesmo recorte devolveram 21.546 linhas cada, mas 14.071, 16.137 e 12.829 registros DISTINTOS. O total sempre bate e o conteudo nunca. Nao pagine: particione o pedido (um municipio por vez, com codigo_municipio) ate caber numa resposta so.",
    "No Previne Brasil a coluna 'percentual' NAO e o resultado do indicador — e cobertura de cadastro (identificados / estimados do IBGE), por isso passa de 100 em metade das linhas. O resultado do indicador e 'percentual_quadrimestre' (numerador / denominador_utilizador). Conferido em 100% das linhas.",
    "Os codigos de indicador do Previne Brasil (10, 20, 30, 40, 50, 70) nao estao documentados no swagger nem na pysus, e um dos sete oficiais nao aparece na API. Da para separa-los pela evidencia: os tres de gestante compartilham denominador identico em 100% dos municipios. Nunca invente o rotulo que falta.",
    "Os 89 indicadores de atencao primaria do MGDI (equipes, saude bucal, Academia da Saude, Farmacia Popular, telessaude) sao .csv.zip publicados em demas-dados-abertos.s3.amazonaws.com/csv/<nome>.csv.zip, todos com o MESMO esquema de 25 colunas: uma receita serve para qualquer um. Quando a mesma base tem API paginada e arquivo publicado, PREFIRA O ARQUIVO.",
    "Nos indicadores MGDI, vl_indicador_calculado_al e a AMAZONIA LEGAL — 773 municipios de 9 UFs, zero nas demais linhas. O nome nao diz isso. As demais colunas agregadas (_rs regiao de saude, _ms macrorregiao, _uf, _reg, _br) fecham exatamente com a soma dos municipios.",
    "Nos indicadores MGDI, ZERO nao quer dizer ausencia do servico: cada arquivo mede uma MODALIDADE. Dos 502 municipios com zero equipes de Saude Bucal 40h, 147 (29%) tem equipe na modalidade de carga horaria diferenciada, contada em outro arquivo.",
    "Nem todo indicador do MGDI e somavel: equipes, polos e centros pertencem a um municipio so e a soma bate com o total nacional, mas 'pessoas atendidas' nao fecha (a mesma pessoa e atendida em mais de um municipio). Antes de somar por municipio, veja a unidade de medida — quando conta pessoas, use a coluna agregada que o arquivo ja traz.",
    "A periodicidade dos indicadores MGDI VARIA: uns sao mensais, outros trazem so dezembro de cada ano, outros junho. co_anomes no formato AAAAMM nao garante serie mensal, e comparar 'o mais recente de cada indicador' compara meses diferentes. Confira os meses presentes antes de plotar.",
    "No cadastro de UBS (47.910 unidades), LATITUDE e LONGITUDE vem como texto com virgula E ponto misturados no mesmo arquivo — sem str.replace(',', '.') viram NaN e o mapa sai vazio sem erro; 4% nao tem coordenada. A coluna UF guarda o CODIGO do IBGE (41 = PR), nao a sigla. E o retangulo 'do Brasil' (-34 a 6, -74 a -34) reprova as UBS de Fernando de Noronha, que ficam a leste de -34.",
    "Ausencia no arquivo nao e ausencia de rede: 83 municipios nao tem nenhuma UBS cadastrada, e 67 deles (81%) tem equipe de saude bucal custeada. O maior e Araruama (RJ), com 137 mil habitantes. Antes de concluir que falta servico, cruze com outro registro.",
    # --- a propria biblioteca -------------------------------------------
    "CORRIGIDO PELA EQUIPE NA 2.10.6: a pysus passou a declarar PyYAML (>=6.0.1,<7.0.0) entre as dependencias. Ate a 2.10.5 ela importava 'yaml' na inicializacao sem declarar, e 'pip install pysus' num ambiente limpo falhava no 'import pysus' com ModuleNotFoundError. Conferido nos tres ambientes: 2.10.4 nao declara, 2.10.5 nao declara, 2.10.6 declara. Mantemos pyyaml no nosso requirements assim mesmo, porque instalacao que nao depende de sorte e mais barata que suporte. Se o usuario montar ambiente novo com pysus < 2.10.6, instale pyyaml junto.",
    "A pysus 2.10 teve cinco versoes em tres dias (2.10.0 a 2.10.4, agosto de 2026) e a documentacao do Read the Docs ficou para tras (ela ainda se identifica como 2.9.0). Para trabalho que precisa ser reproduzivel, fixe a versao (pysus==2.10.4) em vez de usar piso aberto, e confie no codigo da tag antes da documentacao.",
    # --- o SIA tem catorze familias de arquivo -------------------------
    "SENTINELA NAO E DADO, e a mais cara do SIA e o municipio 999999 ('residencia ignorada'). Ela nao vem como NULL: vem como um codigo de seis digitos que passa por qualquer filtro de formato. Medido no PR, jan/2025: 534.351 de 3.700.738 linhas (14,4%) e — porque essas linhas concentram procedimento de alto volume — 37,3% de toda a QUANTIDADE aprovada do estado, mais que o triplo de Curitiba. Num ranking de municipios ela fica em PRIMEIRO lugar. Pior: como 999999 nunca e igual ao municipio que atendeu, toda comparacao PA_MUNPCN <> PA_UFMUN conta residencia desconhecida como deslocamento. Medido: a atencao basica aparece com 47,0% dos procedimentos 'fora do municipio' e o valor real e 1,9% — 45 pontos de engano; ja a alta complexidade nao se move (55,5% dos dois jeitos), porque quem viaja para quimioterapia tem cadastro completo. Ou seja, o erro se concentra onde a resposta certa era obvia. Sempre exclua a sentinela ANTES de comparar ou ranquear, e diga ao usuario quantas linhas sairam.",
    "Codigo de municipio: o DATASUS grava SEIS digitos e o IBGE usa SETE (o setimo e digito verificador). Conferido no SIA: 100% de 200.000 linhas de PA_MUNPCN tem exatamente 6 caracteres (ex.: 411760 = Curitiba e 410690). Ao cruzar com populacao do IBGE, CORTE o codigo do IBGE para 6 (str[:6]) — nunca tente completar o do DATASUS, porque o digito verificador nao e deduzivel sem tabela. Se esquecer, o merge nao da erro: devolve zero linha casada, ou pior, casa so parte e muda o denominador em silencio. Sempre confira len() depois do merge.",
    "As colunas do DATASUS mudam DENTRO do mesmo ano, nao so entre decadas. Medido nos arquivos reais do SIA/PA do Parana: janeiro/2025 tem 60 colunas e marco/2025 tem 61 — apareceu PA_FNTORC (fonte de orcamento) entre um mes e outro, no mesmo estado. E falha DURA, nao silenciosa: pd.read_parquet(caminho, columns=['PA_FNTORC']) levanta ArrowInvalid 'No match for FieldRef.Name' no arquivo de janeiro. Entao um laco que percorre meses quebra no meio. Antes de fixar uma lista de colunas para uma serie, leia o schema de cada arquivo (pyarrow.parquet.read_schema(...).names) e use a INTERSECAO, avisando o usuario de qual coluna nao existe em todo o periodo.",
    "NAO cite os nomes de grupo do SIA que estao no Read the Docs: a pagina 'Datasets' contradiz o proprio codigo da 2.10.6, e o codigo e que esta certo. Ela lista so 7 grupos (falta AB, AC, AT, PS, SA) e erra SEIS dos sete nomes — chama BI de 'Bolsa Integrada' (e Boletim de Producao Ambulatorial Individualizado), AD de 'Administracao' (e APAC de Laudos Diversos), AM de 'Atencao Medica' (e APAC de MEDICAMENTOS), AN de 'Analise da Situacao de Saude' (e APAC de NEFROLOGIA), AQ de 'Atencao a Saude' (e APAC de Quimioterapia) e AR de 'Assistencia Recursal' (e APAC de Radioterapia). O erro do AN e o mais perigoso: quem procura dialise passaria batido. A propria documentacao se contradiz — a pagina 'Working with DATASUS data' descreve AM corretamente como dispensacao de medicamentos de alto custo. Use SIA.group_definitions do codigo instalado, ou o DATASUS.",
    "O SIA nao e so o grupo PA. Sao catorze familias de arquivo, e o nome de cada uma no DATASUS e: PA producao ambulatorial (agregada), BI boletim individualizado, AB acompanhamento a cirurgia bariatrica, ABO pos-cirurgia bariatrica, ACF confeccao de fistula arteriovenosa, AD laudos diversos, AM medicamentos, AMP acompanhamento multiprofissional, AN nefrologia, AQ quimioterapia, AR radioterapia, ATD tratamento dialitico, PS psicossocial, SAD atencao domiciliar. As APAC (todas menos PA e BI) trazem DADO INDIVIDUAL, com identificador do paciente, exames e desfecho.",
    "ATENCAO: os rotulos que a pysus da aos grupos do SIA CONTRADIZEM o DATASUS. Ela chama AB de 'Atencao Basica' (e acompanhamento de cirurgia bariatrica), AT de 'Atencao' (e tratamento dialitico), AC de 'Alta Complexidade' (e confeccao de fistula), PS de 'Procedimentos Especiais' (e psicossocial) e SA de 'Saude' (e atencao domiciliar). Nunca apresente esses nomes ao usuario como definicao, e nunca procure atencao primaria no group='AB' — a producao da atencao primaria esta no PA e no BI (no PR, jan/2024: AB tem 615 linhas contra 3.246.596 do PA).",
    "Nao filtre o SIA pelo parametro group: a pysus junta prefixos diferentes sob o mesmo nome. Medido no PR, jan/2024, group='AM' devolve DOIS arquivos — AMPR2401 (311.217 linhas, medicamentos) e AMPPR2401 (143 linhas, acompanhamento multiprofissional) — e depois de concatenados nada no DataFrame diz de qual arquivo veio cada linha. Selecione pelo prefixo do NOME do arquivo, que e o codigo original do DATASUS.",
    "Pior ainda no SIA: a composicao do grupo muda com o tempo. No PR, group='AB' devolve ABPR1001 em 2010, ABPR1601 E ABOPR1601 em 2016, e so ABOPR2401 em 2024. Uma serie historica montada pelo group troca de base no meio, sem nenhum aviso.",
    "O arquivo ATD (tratamento dialitico) e a base mais rica do SIA para pesquisa clinica: dado individual com AP_CNSPCN (identificador estavel entre meses, permite coorte), acesso vascular, situacao quanto a transplante, sorologias (HIV, HCV, HBsAg) e exames (hemoglobina, albumina, fosforo, PTH, Kt/V). No PR de 2024: 82 mil autorizacoes, 9.158 pacientes, R$ 250 milhoes. Os campos categoricos vem 100% preenchidos; os laboratoriais nao, e o preenchimento varia por estado E por mes — meca antes de calcular media.",
    "Nas APAC do SIA, o motivo de saida (AP_MOTSAI) nao tem tabela documentada, mas da para identificar o obito cruzando com AP_OBITO: no PR de 2024 os codigos 41 e 43 tem 100% de obito e nenhum outro tem. Sao DOIS codigos, nao um — um mes so mostraria apenas o 41.",
    "Quanto o group do SIA mistura, medido no catalogo publico inteiro (55.796 arquivos em 29/08/2026; eram 50.069 dias antes — o catalogo cresce, remeca antes de citar total): o grupo AM reune 4.826 arquivos AM (medicamentos) e 1.985 AMP (acompanhamento multiprofissional) — 29% do grupo NAO e medicamento; o grupo AB reune 635 AB (bariatrica) e 1.592 ABO (pos-bariatrica), ou seja 71% do grupo e ABO. Some sempre pelo prefixo do nome do arquivo, e diga ao usuario qual prefixo entrou na conta.",
    "O grupo BI do SIA (boletim individualizado, o dado por PACIENTE) esta FURADO justamente nos estados grandes, e a falha e silenciosa. Medido no catalogo em 29/08/2026: SP tem so 85 arquivos e nao tem NENHUM de 2011 a 2022; RJ tem 92 e nao tem de 2017 a 2024; PR para em 2015; RS para em 2015. Enquanto isso AC e BA, estados sem arquivo partido, tem 222 cada um e serie completa de 2008 a 2026 — ou seja, quanto MAIOR o estado, pior a cobertura, que e o contrario do que qualquer um esperaria. A causa e o arquivo partido: quando o mes e grande demais o DATASUS quebra em BISP2402_1, _2, _3, e esses 161 arquivos (so MG, RJ e SP) dao dois defeitos diferentes. (a) Os de JANEIRO estao catalogados errado — BISP2401_1 aparece como month=11 e state='_1' —, entao sia('SP', 2024, 1, group='BI') devolve ZERO sem erro nenhum. (b) Os demais meses estao catalogados certo mas NAO BAIXAM: sia('SP', 2024, 2, group='BI') levanta DownloadError 'Too many alias hops'. O parser da 2.10.6 ja trata o sufixo _N corretamente (conferido: devolve BI/SP/2024/mes 1), entao o que sobrou de errado esta no CATALOGO, nao no codigo — sao linhas gravadas por versao antiga que ninguem reprocessou. Antes de dizer a alguem que o estado dele nao produziu, confira a serie ano a ano com list_files.",
    "Janelas de cada familia do SIA, conferidas no catalogo publico (nao no inventario do FTP, que diverge): PA de 1994 a 2026; AD, AM, AMP, AQ e AR de 2008 a 2026; AB 2008-2025; AN 2008-2014 (encerrado); ABO, ACF e ATD de 2014 a 2026; PS 2012-2026; SAD 2012-2016. Fora da janela a consulta devolve lista vazia, sem erro. ATENCAO, isto mudou: a COLUNA 'group' que list_files() devolve esta VAZIA em 100% do catalogo publico — conferido em 29/08/2026 nas oito bases, 176.796 arquivos, todos com group NULL (sia 55.796, cnes 80.192, sih 31.291, ciha 4.722, pni 1.523, sim 1.300, sinan 1.111, sinasc 861). NUNCA leia list_files(...)['group'] nem agrupe por ela: vem tudo NaN. O grupo continua existindo em dois lugares que FUNCIONAM: no caminho do arquivo (public/data/ftp/sia/<GRUPO>/<ano>/<mes>/<UF>/) e no parametro group= do filtro, que confere certo (group='PA' devolve 9.117 arquivos, todos PA; group='AB' devolve 2.227, sendo 1.592 ABO e 635 AB). Para saber o grupo de uma linha, tire do NOME do arquivo, nunca da coluna.",
    "Para contar PESSOAS em dialise, use o arquivo ATD (uma linha por paciente, com AP_CNSPCN) e nao os registros do PA. Medido no PR, junho de 2024: o PA (subgrupo 0305) da 7.514 registros e o ATD 6.658 pacientes distintos — a estimativa pelo PA fica 13% acima.",
    # --- rede: o endereco que ninguem espera ---------------------------
    "O catalogo duckdb da pysus e de UM PROCESSO SO. Dois processos que usem pysus ao mesmo tempo brigam pelo arquivo e o segundo morre com duckdb.IOException 'Cannot open file ... catalog.duckdb: o arquivo ja esta sendo usado por outro processo', que chega ao usuario como sqlalchemy.exc.OperationalError — nome que nao lembra em nada o problema real. Aconteceu duas vezes na nossa bancada: uma validacao concorrente derrubou um notebook que passa sozinho, e um teste rodado durante a validacao caiu no mesmo lugar. Neste aplicativo nao ha risco (o kernel e um so, e a janela de versoes consulta por httpx, nao pelo catalogo), mas se o usuario abrir DOIS notebooks baixando ao mesmo tempo, e isto que vai acontecer. Rode um de cada vez.",
    "A pysus NAO baixa direto do DATASUS: antes de qualquer arquivo ela consulta um catalogo hospedado em nbg1.your-objectstorage.com (bucket 'pysus', caminho public/catalog_<base>.duckdb). Sao 11 catalogos, de 1 MB ate 128 MB (o do CNES). Liberar so os enderecos do DATASUS num firewall NAO faz a biblioteca funcionar.",
    "Erro de rede na pysus quase nunca e internet lenta. Em rede de prefeitura, hospital ou empresa, o equipamento nao responde ao endereco bloqueado e a espera termina em ConnectTimeout — a mensagem fala em tempo esgotado e o usuario tenta de novo achando que vai passar. Se a conexao TCP na porta 443 funciona mas a negociacao TLS expira, e bloqueio seletivo de destino, nao porta fechada. Nunca tente 'consertar o codigo' nesse caso: o codigo esta certo.",
    "O que pedir a TI: liberacao de *.your-objectstorage.com por HTTPS, por NOME DE DOMINIO e nao por IP (e nuvem, os IPs mudam); verificar se a inspecao de TLS esta interferindo; e garantir que o proxy preserve requisicoes HTTP Range e respostas 206 Partial Content — o catalogo e lido em pedacos, e sem isso uma consulta simples passa a baixar ate 128 MB. Somar a isso ftp.datasus.gov.br (FTP, porta 21), apidadosabertos.saude.gov.br e dadosabertos.saude.gov.br.",
    "Se o usuario tentar contornar a rede bloqueada com o 4G do celular, avise: conectar no Wi-Fi do celular NAO basta. Com o cabo de rede ligado o Windows continua roteando tudo pela Ethernet, porque escolhe pela metrica das interfaces, e o erro se repete. E preciso desconectar o cabo ou desativar o adaptador Ethernet. Nao sugira alterar metricas, rotas ou adaptadores por conta propria em computador institucional.",
    "api.github.com e github.com sao enderecos diferentes e os filtros de rede os liberam separadamente: e comum a pagina do GitHub abrir no navegador enquanto a API esta bloqueada. Se o usuario disser que a verificacao de atualizacoes falha mas o download pelo site funciona, e exatamente esse o caso — nao e a internet dele. Antes da 1.8.13 o aplicativo dizia 'verifique sua conexao com a internet' e mandava o usuario procurar um problema que nao existia.",
    "No Windows o Python usa o proxy configurado no sistema mesmo depois de o computador trocar de rede. Um notebook de trabalho levado para o 4G do celular continua tentando falar com o proxy da instituicao, que agora e inalcancavel — entao 'troquei de rede e continua falhando' NAO descarta a hipotese de bloqueio institucional. Para conferir: urllib.request.getproxies().",
    "VPN ligada quebra o acesso ao DATASUS. Os sites do governo brasileiro (saude.gov.br, datasus.gov.br) recusam conexao vinda de IP estrangeiro: o TCP na porta 443 abre e a conexao e derrubada na negociacao TLS, sempre por volta de 20 segundos. O sintoma e IDENTICO ao de rede institucional bloqueada e a solucao e oposta — desligar a VPN, nao pedir liberacao. Pior, o estado engana pela metade: o catalogo da PySUS fica num provedor que nao bloqueia, entao downloads de CNES e SIA continuam funcionando enquanto tudo que e .gov.br falha. Medido: 19,7s ate o reset com VPN, 0,7s e HTTP 200 sem ela.",
    # --- atencao primaria: o que o SIA nao tem ------------------------
    "A Portaria GM/MS 2.148/2017 encerrou, na competencia agosto/2017, a importacao dos dados do e-SUS Atencao Basica para o SIA. Desde entao a producao da APS vai para o SISAB/SIAPS, nao para o SIA. Consequencia medida no PR, janeiro de 2025: das 2.106 UBS cadastradas (CNES tipo 02), apenas 1.010 aparecem com QUALQUER registro no SIA/PA — 48%. E as UBS respondem por 4,4 milhoes de ~30 milhoes de procedimentos aprovados no estado. NUNCA leia ausencia no SIA como ausencia de producao da unidade.",
    "PA_INE (equipe da APS) existe no layout do SIA/PA mas quase nunca vem preenchido: no PR de janeiro de 2025 sao 16.801 registros com INE util em 3.762.992 — 0,45%, e apenas 199 equipes distintas no estado inteiro. Nao construa analise por equipe em cima do PA_INE; ela devolvera quase nada. Para equipe, use o Relatorio de Validacao do SISAB.",
    "Os valores reais de PA_DOCORIG no SIA/PA sao CINCO, nao quatro: I (BPA individualizado, 68% dos registros), P (APAC principal), C, S (APAC secundario) e B. Varias fontes citam so B/I/P/S e esquecem o C, que aparece 473 mil vezes num unico mes do PR. Conte sempre o que existe no arquivo antes de assumir a tabela de codigos.",
    "O arquivo CNES grupo ST tem 208 colunas e NENHUMA com o nome do estabelecimento (nao ha NOME, FANTASIA nem RAZAO SOCIAL). Da para identificar a unidade por CNES, municipio (CODUFMUN) e tipo (TP_UNID, onde 02 = Centro de Saude/UBS), mas nao por nome. Se o usuario quiser achar 'a UBS tal', avise que o nome precisa vir de outra fonte.",
    "Tamanho real do SIA/PA: um mes de UM estado (PR, janeiro de 2025) sao 64 MB em disco, 3,76 milhoes de linhas e 60 colunas — que viram 11,1 GB em memoria se carregados inteiros, e 1,9 GB lendo so 10 colunas. Ler colunas selecionadas nao e otimizacao, e requisito: sem isso o kernel morre. Use pd.read_parquet(caminho, columns=[...]) sobre o arquivo que a pysus ja baixou.",
    "A coluna PA_SRC_C NAO existe no SIA/PA, embora seja citada em varias listas de campos. Confira df.columns antes de usar qualquer campo que voce nao viu com os proprios olhos naquele arquivo.",
    "pysus.atencao_primaria() existe na 2.10.x e mira Previne Brasil/SISAB pelo portal de dados abertos, mas tem duas limitacoes: so baixa recursos cuja URL termina exatamente em '.csv' (ignora '.csv.zip', que e formato comum la), e se a categoria vier vazia devolve um DataFrame VAZIO sem erro nem aviso. Se o usuario receber nada dessa funcao, o problema provavelmente nao e o codigo dele.",
    "Para producao da APS por UBS e por equipe, a fonte publica e o Relatorio de Validacao do SISAB, em sisab.saude.gov.br/paginas/acessoRestrito/relatorio/federal/envio/RelValidacao.xhtml — apesar de 'acessoRestrito' no caminho, ele NAO exige login. E um formulario JSF: pegue javax.faces.ViewState, monte o POST e acione o link Csv. Descubra os nomes dos campos pelo conteudo das opcoes, nunca pelos ids (j_idt70 etc.), que mudam a cada versao do site. O CSV vem em ISO-8859-1 com 7 linhas de cabecalho antes da linha 'IBGE;'.",
    "Queda de indicador na competencia mais recente da APS quase sempre e informacional, nao assistencial: pode ser atraso de envio, processamento pendente ou validacao. Antes de dizer que uma equipe produziu menos, confira o calendario de envio e compare com o total do municipio — se a participacao da unidade ficou estavel e o total caiu, a queda e do processamento. Medido na pratica: uma UBS de Foz do Iguacu manteve ~4% do municipio em tres competencias enquanto o total municipal caiu de 45.793 para 34.500 fichas.",
    "Nao compare serie do SISAB com serie do SIAPS como se fosse continua. O SIAPS foi instituido em 2025 (Portaria GM/MS 7.639/2025) e substitui o SISAB de forma PROGRESSIVA — a formulacao oficial do Ministerio e essa, nao 'SISAB descontinuado'. Relatorios e paginas do SISAB seguem no ar durante a transicao. Quebra tecnologica pode parecer mudanca assistencial.",
    "Denominadores da APS nao sao intercambiaveis: populacao cadastrada, populacao vinculada, populacao residente, populacao esperada e usuarios atendidos medem coisas diferentes. Cadastro nao equivale a uso, e cadastro pode estar duplicado ou desatualizado. Sempre declare qual denominador foi usado antes de apresentar qualquer proporcao da atencao primaria.",
    "Nao compare equipes de tipos diferentes na APS: eSF, eAP, eSB e eMulti tem atribuicoes, composicao e parametros distintos, e produzem volumes que nao sao comparaveis entre si. Estratifique pelo tipo de equipe antes de qualquer ranking. E lembre: ausencia de registro nao prova ausencia de cuidado.",
    "pysus.mask_data() e unmask_data() quebram com ModuleNotFoundError: No module named 'cryptography' — a pysus usa a biblioteca sem declara-la, exatamente como faz com o pyyaml. Neste aplicativo funciona porque declaramos cryptography no nosso requirements — ate 29/08/2026 ela so chegava de carona, por um extra opcional do PyJWT; no Colab e preciso '%pip install cryptography' antes. Os tres metodos NAO sao 'mais fraco' e 'mais forte', e sim escolhas diferentes do que sobra para analisar, medido em 20.000 linhas do SIA/AC com 377 profissionais distintos: encrypt usa Fernet, que embaralha com sal aleatorio a cada chamada, entao o MESMO CNS vira valores DIFERENTES e os 377 profissionais viraram 20.000 distintos — quem receber esse arquivo e contar profissionais conta linhas achando que conta pessoas, e o numero sai alto sem erro na tela; e o unico reversivel, com a chave. hash e sha256 SEM SAL, determinista, preserva contagem e juncao (377 continuaram 377) — mas por ser determinista e PSEUDONIMIZACAO, nao anonimizacao: quem tem a lista de CNS possiveis (o CNES publica) passa a lista pela mesma conta e reverte; medido, 100% dos hashes voltaram ao original em menos de um segundo. redact vira *** e nao volta nem com chave (unmask levanta InvalidToken). Regra: redact para publicacao aberta, hash para colega de confianca que precisa agrupar, encrypt so quando voce mesmo precisa recuperar depois — e nunca para contar.",
    "NUNCA chame mask_data sem columns=. A auto-deteccao procura pedaco de texto no NOME da coluna (CPF, NOME, NASC, RG, ENDERECO, TELEFONE, EMAIL, CEP) e erra dos dois lados, conferido nos arquivos reais. No SIA/PA ela marca PA_INCURG (incremento de urgencia, valor administrativo) porque as letras RG aparecem dentro de INCURG — e na ABO marca AB_DTCIRG2, a data da segunda cirurgia bariatrica, pelo RG dentro de CIRG. E NAO marca PA_CNSMED, que e o CNS do profissional — o identificador de verdade, preenchido em 100% das linhas. No SINASC ela marca CODMUNNASC, LOCNASC e TPNASCASSI, que sao as colunas DA ANALISE, porque todas contem NASC: aceitar o padrao criptografa o municipio de nascimento e depois voce tenta agrupar por ele. CNS nao esta na lista de padroes, entao nas APAC ela tambem deixa passar AP_CNSPCN, que e o CNS do PACIENTE (conferido em ABO, ACF e AD do AC/2024: devolveu AP_CNPJCPF e AP_CEPPCN, nunca AP_CNSPCN). Liste as colunas do arquivo e decida uma a uma.",
    "A Portaria GM/MS 7.639/2025 (verificada no DOU de 22/07/2025) tirou o SISAB da lista de bancos nacionais de alimentacao obrigatoria e pos o Siaps no lugar (art. 294), e mandou exportar a Atencao Basica ao CMD exclusivamente pela base do Siaps (art. 302). Ela tambem cria no Siaps um modulo de Atencao Domiciliar para EMAD e EMAP, tornando o Siaps o sistema vigente para financiar esses servicos (art. 307) — o que conversa com o grupo SAD do SIA, que e atencao domiciliar e cujo catalogo para em 2016.",
    "Fichas da APS sem INE nao sao erro de cadastro. O art. 311 da Portaria de Consolidacao 1/2017, na redacao da 7.639/2025, obriga a enviar ao Siaps TODOS os profissionais lotados diretamente em estabelecimento de atencao primaria, INCLUSIVE os que nao fazem parte de equipe com Identificador Nacional de Equipe. Entao, ao ver linhas sem INE no Relatorio de Validacao, nao diga que e cadastro incompleto: e o que a norma prevê. Medido numa UBS de Foz do Iguacu: 29 a 50 fichas por mes sem equipe, ao lado de quatro equipes identificadas.",
    "No Relatorio de Validacao do SISAB, o tipo de ficha decide quais equipes aparecem: pedindo 'Atendimento Individual' voce nao ve as equipes de saude bucal, que so aparecem em 'Atendimento Odontologico'. Se uma equipe conhecida sumir do resultado, verifique o filtro de ficha antes de concluir que ela nao produziu.",
    "O Relatorio de Validacao do SISAB conta FICHAS enviadas e validadas, nao procedimentos nem consultas. Uma ficha pode carregar varias informacoes. Ele responde 'a unidade esta enviando, quais equipes, quanto foi aprovado e o que foi reprovado' — nao 'quantos atendimentos foram feitos'. Nao apresente esses numeros como producao assistencial.",
]


class LessonStore:
    def __init__(self) -> None:
        self.lessons: list[dict] = []
        self.load()

    # ------------------------------------------------------------------
    def load(self) -> None:
        """Carrega as lições, juntando as guardadas com as desta versão.

        Cuidado histórico: até a versão 1.8.3 este método só criava o arquivo
        quando ele ainda não existia. Quem já tinha o aplicativo instalado
        ficava congelado nas lições da primeira instalação e nunca recebia as
        novas — o aplicativo atualizava, e a parte que ele sabe sobre o
        DATASUS, não.
        """
        guardadas: list[dict] = []
        try:
            if LESSONS_FILE.exists():
                carregado = json.loads(LESSONS_FILE.read_text(encoding="utf-8"))
                if isinstance(carregado, list):
                    guardadas = [x for x in carregado if isinstance(x, dict) and x.get("licao")]
        except Exception:  # noqa: BLE001
            guardadas = []          # arquivo corrompido: recomeça das sementes

        self.lessons = self._sincronizar(guardadas)
        try:
            self.save()
        except Exception:  # noqa: BLE001
            pass

    def _sincronizar(self, guardadas: list[dict]) -> list[dict]:
        """Junta o que o aplicativo aprendeu sozinho com as lições da versão.

        As lições aprendidas com erros reais são do usuário e ficam sempre.
        As pré-carregadas são nossas e passam a ser as desta versão: se uma
        saiu do código, saiu porque foi corrigida ou superada, e mantê-la faria
        o assistente seguir uma regra que já sabemos errada.
        """
        aprendidas = [x for x in guardadas if x.get("origem") != "pre-carregada"]
        ja_conhecidas = {self._norm(x["licao"]) for x in aprendidas}
        hoje = str(date.today())
        sementes = [
            {"licao": texto, "origem": "pre-carregada", "data": hoje}
            for texto in SEED_LESSONS
            if self._norm(texto) not in ja_conhecidas
        ]
        return sementes + aprendidas

    def save(self) -> None:
        APP_DIR.mkdir(parents=True, exist_ok=True)
        LESSONS_FILE.write_text(
            json.dumps(self.lessons[-MAX_LESSONS_STORED:], ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

    # ------------------------------------------------------------------
    @staticmethod
    def _norm(text: str) -> str:
        text = unicodedata.normalize("NFKD", text.lower().strip())
        return "".join(c for c in text if not unicodedata.combining(c))

    def add(self, licao: str, origem: str = "erro corrigido") -> bool:
        """Guarda uma nova lição; devolve False se já existia uma equivalente."""
        licao = " ".join(licao.split())
        if not licao or len(licao) < 15:
            return False
        norm = self._norm(licao)
        for existing in self.lessons:
            if self._norm(existing["licao"]) == norm:
                return False
        self.lessons.append(
            {"licao": licao, "origem": origem, "data": str(date.today())}
        )
        self.save()
        return True

    def for_prompt(self) -> str:
        """Bloco de texto com as lições, para injetar no prompt de sistema.

        As pré-carregadas nunca são cortadas: são elas que evitam os erros que
        travam o notebook (o nest_asyncio, o group de cada base, as bases que
        estouram a memória). Um corte simples pelas últimas do arquivo
        derrubaria justamente as primeiras da lista, que são as mais básicas.
        Quando não cabe tudo, quem sai são as aprendidas mais antigas.
        """
        sementes = [x for x in self.lessons if x.get("origem") == "pre-carregada"]
        aprendidas = [x for x in self.lessons if x.get("origem") != "pre-carregada"]

        espaco = MAX_LESSONS_IN_PROMPT - len(sementes)
        if espaco > 0:
            selecionadas = sementes + aprendidas[-espaco:]
        else:
            selecionadas = sementes

        if not selecionadas:
            return ""
        return "\n".join(f"- {item['licao']}" for item in selecionadas)

    def count(self) -> int:
        return len(self.lessons)
